### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by aneeskhan47** [khalyomede/laravel-seed#1]
@khalyomede 

Hi i really like this package, can you please add support for laravel 8

**Comment by khalyomede** [comment]
Hello, @aneeskhan47, thanks, means a lot! I'll work on it tomorrow I'll let you know if I can release something tomorrow then 😉

**Comment by aneeskhan47** [comment]
@khalyomede  #2

**Comment by khalyomede** [comment]
Thanks a lot @aneeskhan47 🙏 It has been deployed on [v0.2.0](https://github.com/khalyomede/laravel-seed/releases/tag/v0.2.0).
